export enum EnumLoader {
  SAVE_INQUIRY = 'SAVE_INQUIRY',
  SAVE_QUOTE = 'SAVE_QUOTE',
  CANCEL_BOOKING = 'CANCEL_BOOKING',
  UPDATE_PERSONAL_INFO_ADDRESS = 'UPDATE_PERSONAL_INFO_ADDRESS',
  GENERATING_PLAN_URL = 'GENERATING_PLAN_URL',
  RESET_QUOTE = 'RESET_QUOTE',
  PAYMENT_METHOD = 'PAYMENT_METHOD',
  LOAD_QUOTE = 'LOAD_QUOTE',
}
