export const REACT_APP_API_KEY: string = process.env.REACT_APP_API_KEY || ''
export const REACT_APP_API_URL: string = process.env.REACT_APP_API_URL || ''
export const REACT_APP_API_DOMAIN_URL: string = process.env.REACT_APP_API_DOMAIN_URL || ''
export const REACT_APP_AUTOCOMPLETE: string = process.env.REACT_APP_AUTOCOMPLETE || ''
export const PUBLIC_URL: string = process.env.PUBLIC_URL || ''
export const REACT_APP_STRIPE_PUBLIC_KEY: string = process.env.REACT_APP_STRIPE_PUBLIC_KEY || ''
