name: react-production
on:
  push:
    branches: [main]
jobs:
  docker-prod:
    runs-on: ubuntu-latest
    # environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          build-args: |
            GH_TOKEN=${{ secrets.GH_TOKEN }}
            GH_USERNAME=${{ secrets.GH_USERNAME }}
            GH_REPO=${{ secrets.GH_REPO }}
            SOURCE_ENV=production
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fixglass-react:production
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
